steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/k8s-the-hard-way-227315/github.com/dmesser/operatorhubio:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/k8s-the-hard-way-227315/github.com/dmesser/operatorhubio:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'operatorhubio', '--image=gcr.io/k8s-the-hard-way-227315/github.com/dmesser/operatorhubio:$SHORT_SHA', '--region=us-central1', '--platform=managed']